# Generated by Django 5.0.6 on 2024-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_price_post_town_alter_post_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner',
            new_name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ImageField(default='any', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
