# Generated by Django 5.0.6 on 2024-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_banner_post_image_post_category_post_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='any', max_length=15),
        ),
    ]
