# Generated by Django 5.0.6 on 2024-07-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_user_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked',
            name='first_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='blocked',
            name='second_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='accounts.userprofile'),
        ),
    ]
