# Generated by Django 5.0.7 on 2024-07-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_blocked_first_user_alter_blocked_second_user'),
        ('posts', '0008_post_parent_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.userprofile'),
        ),
    ]
