# Generated by Django 5.1 on 2024-08-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_date'),
        ('posts', '0011_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposted',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposted_by', to='accounts.userprofile'),
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
