# Generated by Django 5.1 on 2024-08-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_date'),
        ('posts', '0014_alter_post_reposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reposted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposted_posts', to='accounts.userprofile'),
        ),
    ]
